[package]
name = "rust-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
assert_cmd = "2.0.16"
assert_fs = "1.1.2"
clap = { version = "4.5.28", features = ["derive"] }
predicates = "3.1.3"
signal-hook = "0.3.17"
